FROM node:16.13.2-alpine as builder
RUN apk update && apk add yarn 

RUN mkdir app
WORKDIR app

COPY package*.json ./
RUN yarn install --network-timeout 1000000000


COPY . ./
RUN rm -rf .env.dev 
RUN yarn build


FROM nginx:alpine
COPY --from="builder" /app/dist /dist
COPY nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
